import {StyleSheet} from React;

export const styles = StyleSheet.create({
  vAlignTextMiddle: {
    display: flex,
    flexDirection: column,
    justifyContent: center,
  },

  dancingScriptNormalWhite48px: {
    color: "#FFFFFF",
    fontFamily: "dancing script",
    fontSize: "medium",
    fontWeight: 400,
    fontStyle: normal,
  },
  gabrielaNormalCeruleanFrost24px: {
    color: "#7C97CE",
    fontFamily: "gabriela",
    fontSize: "small",
    fontWeight: 400,
    fontStyle: normal,
  },
  overlapGroup4: {
    width: 393,
    display: flex,
    flexDirection: column,
    padding: 14,
    alignItems: center,
    minHeight: 844,
    backgroundColor: "#96c4fb",
  },
  overlapGroup5: {
    width: 219,
    height: 201,
    position: relative,
    marginTop: 69,
    marginRight: 2,
  },
  reese: {
    position: absolute,
    height: 175,
    top: 0,
    left: 21,
    display: flex,
    padding: 22.7,
    justifyContent: flex - end,
    alignItems: flex - end,
    minWidth: 188,
    backgroundColor: "#CAE2FE",
    borderRadius: 87.5,
  },
  intersect: {
    width: 130,
    height: 173,
    objectFit: cover,
  },
  title: {
    display: flex,
    flexDirection: column,
    justifyContent: center,
    color: "#FFFFFF",
    fontFamily: "dancing script",
    fontSize: "medium",
    fontWeight: 400,
    fontStyle: normal,
    position: absolute,
    width: 219,
    height: 75,
    top: 126,
    left: 0,
    stroke: "#7C97CE",
    textAlign: center,
    lineHeight: normal,
  },
  span0: {
    color: "#FFFFFF",
    fontFamily: "dancing script",
    fontSize: "medium",
    fontWeight: 400,
    fontStyle: normal,
    letterSpacing: -2.4,
  },
  span1: {
    color: "#FFFFFF",
    fontFamily: "dancing script",
    fontSize: "medium",
    fontWeight: 400,
    fontStyle: normal,
    letterSpacing: 0,
  },
  span2: {
    color: "#FFFFFF",
    fontFamily: "dancing script",
    fontSize: "medium",
    fontWeight: 400,
    fontStyle: normal,
    letterSpacing: -0.96,
  },
  span3: {
    color: "#FFFFFF",
    fontFamily: "dancing script",
    fontSize: "medium",
    fontWeight: 400,
    fontStyle: normal,
    letterSpacing: -1.44,
  },
  buttons: {
    height: 331,
    marginTop: 48,
    display: flex,
    alianItems: flex - start,
    minWidth: 353,
    gap: 17,
  },
  overlapGroupContainer: {
    width: 168,
    display: flex,
    flexDirection: column,
    alignItems: flex - start,
    minHeight: 331,
    gap: 23,
  },
  overlapGroup2: {
    height: 154,
    display: flex,
    padding: 36,
    alignItems: flex-end,
    minWidth: 168,
    backaroundColor: "#CAE2FE",
    borderRadius: 45,
  },
  place: {
    display: flex,
    flexDirection: column,
    justifyContent: center,
    color: "#7C97CE",
    fontFamily: "gabriela",
    fontSize: "small",
    fontWeight: 400,
    fontStyle: normal,
    height: 31,
    minWidth: 90,
    textAlign: center,
    letterSpacing: 0,
    lineHeight: normal,
  },
  overlapGroup3: {
    height: 154,
    display: flex,
    padding: 15,
    alignItems: flex - start,
    minWidth: 168,
    backgroundColor: "#CAE2FE",
    borderRadius: 45,
  },
  beBRAVE: {
    display: flex,
    flexDirection: column,
    justifyContent: center,
    color: "#7C97CE",
    fontFamily: "gabriela",
    fontSize: "small",
    fontWeight: 400,
    fontStyle: normal,
    height: 31,
    minWidth: 137,
    textAlign: center,
    letterSpacing: 0,
    lineHeight: normal,
  },
  overlapGroup1: {
    height: 154,
    display: flex,
    padding: 32,
    alignItems: flex - end,
    minWidth: 168,
    backgroundColor: "#CAE2FE",
    borderRadius: 45,
  },
  program: {
    display: flex,
    flexDirection: column,
    justifyContent: center,
    color: "#7C97CE",
    fontFamily: "gabriela",
    fontSize: "small",
    fontWeight: 400,
    fontStyle: normal,
    height: 31,
    minWidth: 101,
    textAlign: center,
    letterSpacing: 0,
    lineHeight: normal,
  },
  overlapGroup: {
    height: 154,
    display: flex,
    padding: 46,
    alignItems: flex - start,
    minWidth: 168,
    backgroundColor: "#CAE2FE",
    borderRadius: 45,
  },
  pledge: {
    display: flex,
    flexDirection: column,
    justifyContent: center,
    color: "#7C97CE",
    fontFamily: "gabriela",
    fontSize: "small",
    fontWeight: 400,
    fontStyle: normal,
    height: 31,
    minWidth: 76,
    textAlign: center,
    letterSpacing: 0,
    lineHeight: normal,
  },
  braveLogo: {
    width: 356,
    height: 152,
    alignSelf: flex - end,
    marginTop: 23,
    objectFit: cover,
  },
});
